### PR TITLE
feat: Added Mukul Profile data in Profile.json

### PR DESCRIPTION
**Pull request by mukulpythondev**
Update the Profiles.json to add the my data in it.
image

### CODE REVIEW

**Comment by pushkarydv** [comment]
> Update the Profiles.json to add the my data in it. image

@mukulpythondev 
**Deployment Failure**
**Reason**: JSON Error
**FIx**: JSON docs never end with , at end fix that into your code

**Comment by mukulpythondev** [comment]
Now removed the comma in package.json so sir please merge my pull request

**Review by Keshavjindall — CHANGES_REQUESTED** [review]
bro close the curly braces and add comma in the end too if you wish to add your profile in between two profiles

**Comment by mukulpythondev** [comment]
> bro close the curly braces and add comma in the end too if you wish to add your profile in between two profiles but in case you add in end then no need to add comma in end of it.

Now check i update the screenshot

**Comment by pushkarydv** [comment]
> > bro close the curly braces and add comma in the end too if you wish to add your profile in between two profiles but in case you add in end then no need to add comma in end of it.
> 
> Now check i update the screenshot

@mukulpythondev I've updated your code. You had an error in json basically no comma in end before another object which was making wrong format and deployment failure. 
Anyways fixed it. Merging Now

**Pull request merged**
